language: php

sudo: true

matrix:
  fast_finish: true
  include:
        - php: 7.0
	  env: deps=low
          env: WITH_CRYPTO=true
        - php: 7.1
          env: deps=low
	  env: WITH_CRYPTO=true
before_install:
 - composer install --dev
