language: php

sudo: true

matrix:
  fast_finish: true
  include:
        - php: 7.0
          env: deps=low
        - php: 7.0
          env: WITH_CRYPTO=true
        - php: 7.1
          env: deps=low
  allow_failures:
     php: 7.0
     php: 7.1
before_install:
 - composer install --dev
